### ISSUE TITLE
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream

### ISSUE THREAD

**Issue by dmathewwws** [Podcastindex-org/podping.cloud#65]
Hi, 

Thanks for creating this repo. I'm using hive-watcher.js (on my node backend) and everything works great most of the time, but ever so often (once every 30 mins) the script crashes with the following error:

```
Error occurred parsing stream
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
Reached end of stream
```

Has anyone else run into this? 

Makes me think a block has come back without any rss urls? (but to be honest, thats mostly a guess)

**Comment by daveajones** [comment]
Following up with asks here:  [](https://podcastindex.social/web/@dave/108674881530640935)

**Comment by stevencrader** [comment]
I'll take a look

**Comment by stevencrader** [comment]
I finally had this happen tonight. I believe this happens when the api server returns invalid data or does not return data.

What I do on https://podping.watch/ is restart the watcher from the last block received. This is triggered in the [`end` event handler](https://github.com/Podcastindex-org/podping.cloud/blob/main/hive-watcher-js/hive-watcher.js#L248).

I didn't set this up in the example though. I've prepared the change but want to make sure it works properly. If you want to look at it before I make a PR, see the change in [my branch](https://github.com/stevencrader/podping.cloud/blob/restart-watcher-js/hive-watcher-js/hive-watcher.js#L238).

**Comment by agates** [comment]
Yes, we do the same thing in the python watcher.  Good to know!

**Comment by dmathewwws** [comment]
Thanks @stevencrader :) 

Appreciate you taking the time to look at + fix it!
